server: 
  port: 7000
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eurakeserver9000.com:9000/eureka/
    enabled: true
  instance: 
    instance-id: sharePark-config-server-7000 # 配置注册中心显示出来的微服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址  
spring: 
  application:
    name: shareparking-config-server
  profiles:
    active: native
  cloud: 
    config:
      server: 
        native: #本地配置
          search-locations: classpath:/config
          